### ISSUE TITLE
./install.sh: command not found

### ISSUE THREAD

**Issue by gniuskap** [bder222/NBA-scoreboard#2]
Hi, 

First off, thanks so much for posting this project. It's been a lot of fun trying to get this to work, but running into a few issues. Sorry if these questions are very novice.

I went ahead and followed your steps, I went through the installation portion, but when I try to enter the command

sudo ./install.sh

I get the prompt:

sudo: ./install.sh not found.

I went ahead and followed the steps in to create the install.sh, everything seemingly was created. But after cd back into the NBA-scoreboard directory, I still get the same error when trying to run the sudo install script.

Is there a step I am missing?

Thanks again so much!

**Comment by bder222** [comment]
Thanks for checking out the project! I just tried a fresh install and it looks like I forgot to add a step to make the install script executable. To do this, use the following command (while in the NBA-scoreboard directory) before trying to execute the install.sh script:

`sudo chmod 775 install.sh`

Let me know if this works! Also, since it's the All Star break there won't be anything displayed on the board, but it should start tomorrow (3/11) when there are games.

**Comment by gniuskap** [comment]
Thank you so much! I will try this once I get back to the office tomorrow.

you rock

**Comment by gniuskap** [comment]
Thanks bder222, this seemingly did the trick. However there is another small issue I am running into I will introduce in a separate post.
