### ISSUE TITLE
NBA standings appears to be broken

### ISSUE THREAD

**Issue by jediempi** [bder222/NBA-scoreboard#6]
The last time it successfully updated for me is 2 December 2021. 

When you visit the site: https://sports.core.api.espn.com/v2/sports/basketball/leagues/nba/seasons/2022/types/2/groups/{0}/standings/0

You receive the error: {"error":{"message":"application error","code":404}}

**Comment by bder222** [comment]
The {0} between groups and standings references the argument in the string format command, so that should change to 5 (eastern) or 6 (western). So the correct URLs are 

https://sports.core.api.espn.com/v2/sports/basketball/leagues/nba/seasons/2022/types/2/groups/5/standings/0
https://sports.core.api.espn.com/v2/sports/basketball/leagues/nba/seasons/2022/types/2/groups/6/standings/0

I tried copying the NBA standings script and the request worked for me. If you run the NBA_Standings.py script independently, does it throw an exception?

**Comment by jediempi** [comment]
All is well. The standings were stuck and were not updating. I then took your NBA_Standings code and broke the crap out of it. :) Thank you for the above comment. This helped me get back on track and un-break what I did. Thank you!

**Comment by Blueice119** [comment]
My standings are also stuck on old data. Is there a change to the website that I should make?
